version: '3.5'

services:
  nginx-container:
    container_name: nginx-container
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - php-container
      - database-container
    networks:
      - symfony-network

  php-container:
    container_name: php-container
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - database-container
    networks:
      - symfony-network

  database-container:
    container_name: database-container
    image: mysql:8.0
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - database-container-data:/var/lib/mysql
    networks:
      - symfony-network

volumes:
  database-container-data:
networks:
  symfony-network:
    external: true